name: Test

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - name: Install test dependencies
        run: sudo apt-get update && sudo apt-get install -y jq lua5.4 shellcheck smartmontools util-linux
      - name: Run tests
        run: make test
